# Generated by Django 3.2.12 on 2022-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u4uapp', '0002_carrera_universidadcarrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='universidades',
            field=models.ManyToManyField(to='u4uapp.Universidad'),
        ),
        migrations.DeleteModel(
            name='UniversidadCarrera',
        ),
    ]
