# Generated by Django 3.2.12 on 2022-10-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u4uapp', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='universidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='u4uapp.universidad'),
            preserve_default=False,
        ),
    ]
