# Generated by Django 3.1.1 on 2022-10-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u4uapp', '0005_comentario_universidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreraesp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrec', models.TextField(max_length=256)),
                ('area', models.TextField(max_length=256)),
                ('puntaje', models.CharField(max_length=256)),
                ('porcentaje', models.CharField(max_length=256)),
                ('duracion', models.CharField(max_length=256)),
                ('ubicacion', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateField(default='2022-10-10'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
