# Generated by Django 3.1.1 on 2022-10-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u4uapp', '0006_auto_20221010_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='infog',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
    ]
